from PIL import Image
from transformers import BlipProcessor, BlipForConditionalGeneration

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

def infer(image_path: str) -> str:
    """
    Generates caption for image using BLIP model

    Args
        image_path: saved image path

    Returns 
        [str]: caption generated by the model

    """
    try:
        image = Image.open(image_path).convert('RGB')

        inputs = processor(image, return_tensors='pt')
        output = model.generate(**inputs)
        result = processor.decode(output[0], skip_special_tokens=True).capitalize() 

        return result

    except Exception as e:
        raise e