from PIL import Image
from api import model, processor

def infer(image_path: str) -> str:
    """
    Generates caption for image using BLIP model

    Args
        image_path: saved image path

    Returns 
        [str]: caption generated by the model

    """
    try:
        image = Image.open(image_path).convert('RGB')

        inputs = processor(image, return_tensors='pt')
        output = model.generate(**inputs, max_length=50, top_p=0.80, temperature=1.0)
        result = processor.decode(output[0], skip_special_tokens=True).capitalize() 

        return result

    except Exception as e:
        raise e